version: '3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"
        network_mode: host
    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        # links:
        #    - rabbit
        depends_on:
            - rabbit
        user: nobody
        network_mode: host

    shell:
        image: ubuntu
        network_mode: host
